// PostgREST row fixtures (snake_case, as the DB returns them). Used by the MSW
// handlers so data-layer tests exercise the real HTTP → mapper path. Kept
// deliberately "rich" (every column populated) to pin the snake→camel mapping.

export const regionRow = {
  id: "reg-1",
  name: "Одеська область",
  slug: "odeska",
};

export const districtRow = {
  id: "dist-1",
  region_id: "reg-1",
  name: "Одеський район",
  name_en: "Odesa district",
  slug: "odeskyi",
  subtitle: "підзаголовок",
  subtitle_en: "subtitle",
  description: "опис",
  description_en: "description",
  detailed_info: "детально",
  image_url: "https://img/dist.jpg",
  video_url: "https://vid/dist.mp4",
  reel_url: "https://reel/dist.mp4",
  sort_order: 2,
};

export const cityRow = {
  id: "city-1",
  district_id: "dist-1",
  name: "Біляївка",
  name_en: "Bilyaivka",
  slug: "bilyaivka",
  settlement_type: "місто",
  weather_city_name: "Bilyaivka",
  subtitle: "підзаголовок міста",
  subtitle_en: "city subtitle",
  description: "опис міста",
  description_en: "city description",
  detailed_info: "детально про місто",
  image_url: "https://img/city.jpg",
  video_url: "https://vid/city.mp4",
  reel_url: "https://reel/city.mp4",
  sort_order: 1,
};

export const objectRow = {
  id: "obj-1",
  district_id: "dist-1",
  city_id: "city-1",
  type: "attraction",
  name: "Музей",
  name_en: "Museum",
  slug: "muzei",
  published: true,
  subtitle: "пам'ятка",
  subtitle_en: "landmark",
  description: "опис об'єкта",
  description_en: "object description",
  detailed_info: "детально",
  detailed_info_en: "details",
  image_url: "https://img/obj.jpg",
  video_url: "https://vid/obj.mp4",
  map_url: "https://maps.google.com/?q=46.5,30.7",
  address: "вул. Прикладна 1",
  address_en: "1 Example St",
  phone: "+380000000000",
  website: "https://example.org",
  event_dates: "2026-07-01",
  hours: "10:00-18:00",
  hours_en: "10am-6pm",
  amenities: "wifi",
  amenities_en: "wifi",
  tourism_types: ["culture"],
  reel_url: "https://reel/obj.mp4",
  reel_image_url: "https://img/obj-reel.jpg",
  venue_id: "venue-1",
  repertoire: "2026-07-01|Концерт|19:00",
  hero_font_size: "48px",
};

export const contentCardRow = {
  id: "card-1",
  page_key: "index",
  section_key: "directions",
  card_type: "destination",
  title: "Напрямок",
  title_en: "Direction",
  subtitle: "підзаголовок картки",
  subtitle_en: "card subtitle",
  image_url: "https://img/card.jpg",
  href: "/raion/odeskyi",
  city_id: null,
  district_id: "dist-1",
  region_id: null,
  sort_order: 3,
  published: true,
  payload: { badge: "new" },
};
